#!/bin/bash

DIR=$(find "${HOME}/.config")
echo "------------------------------------"
echo "Dirctories in ${HOME}/.config/:"
echo "------------------------------------"

for dir in $DIR; do
    [[ -f "$dir" ]] && continue
    for catg in "${dir[@]}"; do
    echo "${catg#"${HOME}/.config"}"
 done | sort
done

echo ""
echo "--------------------------"
echo "Files in each direcotry:"
echo "--------------------------"
echo ""

for file in $DIR; do
    [[ -d "$file" ]] && continue
    for catg in "${file[@]}"; do
    echo "${catg#"${HOME}/.config"}"
 done | sort
done


