#!/bin/bash

#Display system information

host=$(hostname)
date=$(date)
ker=$(uname -r)

echo "==== System Information ===="
echo "Hostname: ${host}"
echo "Date: ${date}"
echo "Kernel version: ${ker}"

